### ISSUE TITLE
تبدیل میلادی به شمسی(جلالی)

### ISSUE THREAD

**Issue by J-Arji** [jalaali/SwiftJalaali#1]
سلام
من می توانم با استفاه از این تاریخ میلادی که دارم رو به شمسی برگردونم؟؟

**Comment by behrang** [comment]
بله. اگر چه این کد در زمان
Swift 1
نوشته شده و ممکن است کار نکند. اگر مشکل داشتید بگویید تا بررسی شود.

**Comment by J-Arji** [comment]
عذر میخوام آیا دیت پیکر فارسی به زبان سویفت وجود دارد ؟؟ 
date picker

**Comment by behrang** [comment]
من چيزي نديده ام. البته به دنبال آن هم نگشته ام.

On Mon, Apr 11, 2016 at 11:02 PM, J-phantom notifications@github.com wrote:
عذر میخوام آیا دیت پیکر فارسی به زبان سویفت وجود دارد ؟؟
date picker
