### ISSUE TITLE
نحوی نمایش تاریخ یکسال 

### ISSUE THREAD

**Issue by kavoskhajavi** [jalaali/SwiftJalaali#2]
با سلام 
من میخواستم با استفاده از این کامپوننت تاریخ شمسی را در یک دیالوگ نمایش دهم 
لطفا در صورت امکان راهنمایی کنید 
با تشکر

**Comment by behrang** [comment]
درود
این کتابخانه الگوریتم تبدیل تاریخ گریگوری به جلالی را دارد. هر تاریخ میلادی که به آن بدهید، معادل جلالی را بر میگرداند.
سپاس
